import Vue from 'vue';
import {Button, Form, FormItem, Input, Container, Header, Main, Aside, Dropdown, DropdownItem, DropdownMenu, Menu, MenuItem, Submenu, MenuItemGroup, Breadcrumb, BreadcrumbItem, Card, Row, Col, Table, TableColumn, Pagination, Dialog, Select, Tabs, TabPane, Switch, Radio, RadioButton, RadioGroup, DatePicker, Divider, Alert, Tooltip, Loading, Popover, PageHeader, Checkbox, CheckboxGroup, Option, Image, Message, MessageBox, Avatar, Tag, Upload, Scrollbar, Collapse, CollapseItem, Steps, Step, Backtop, ColorPicker, Slider, InputNumber, Calendar, Carousel, CarouselItem, Tree, Badge, InfiniteScroll, Transfer} from 'element-ui';

Vue.use(Button);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Input);
Vue.use(Container);
Vue.use(Header);
Vue.use(Main);
Vue.use(Aside);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Submenu);
Vue.use(MenuItemGroup);
Vue.use(Breadcrumb);
Vue.use(BreadcrumbItem);
Vue.use(Card);
Vue.use(Row);
Vue.use(Col);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(Select);
Vue.use(Option);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Switch);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(RadioButton);
Vue.use(DatePicker);
Vue.use(Divider);
Vue.use(Alert);
Vue.use(Image);
Vue.use(Tooltip);
Vue.use(Loading.directive);
Vue.use(Popover);
Vue.use(PageHeader);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Avatar);
Vue.use(Tag);
Vue.use(Upload);
Vue.use(Scrollbar);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Steps)
Vue.use(Step);
Vue.use(Backtop);
Vue.use(ColorPicker);
Vue.use(Slider);
Vue.use(InputNumber);
Vue.use(Calendar);
Vue.use(Image);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Tree);
Vue.use(Badge);
Vue.use(InfiniteScroll);
Vue.use(Transfer);
// 对于 js 中使用的组件需要全局挂载.
Vue.prototype.$message = Message;
Vue.prototype.$messageBox = MessageBox;
Vue.prototype.$loading = Loading.service;